<img src="https://raw.githubusercontent.com/yGiovana/yGiovana/snake-output/snake.svg" alt="Snake animation" />

###

<div align="center">
  <img src="https://visitor-badge.laobi.icu/badge?page_id=yGiovana.yGiovana&"  />
</div>

###
